version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Movilidad_2026!
      - MSSQL_PID=Developer
    volumes:
      - mssql_data:/var/opt/mssql
    # SQL Server tarda ~15-30 s en estar listo. Despu√©s ejecutar scripts/01-create-database.sql

volumes:
  mssql_data: